#!/bin/sh

[ $# -ne 0 ] && exec < "$1"
XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR-"/run/user/$(id -u)"}"

datadir="$XDG_RUNTIME_DIR/feeds/"
mkdir -p "$datadir" || exit

outdir=
trans=

while read -r name subdir url leftovers; do
	case "$name" in
		OUTDIR)
			outdir="$subdir/"
			[ "${outdir#'~/'}" != "$outdir" ] && outdir="$HOME${outdir#'~'}"  # ~username not supported
			;;
		TRANS ) trans="-t $subdir" ;;
		''    )                    ;;
		'#'*  )                    ;;
		*     )
			(
				IFS="$IFS\""
				curl -SsL -z "$datadir$name.feed" -o "$datadir$name.feed" "$url" &&  # --etag-compare "$datadir$name.etag" --etag-save "$datadir$name.etag"
					${FEEMBOX-feembox} $trans $leftovers "$outdir$subdir" "$datadir$name.feed"
			) &
			;;
	esac
done
wait
